travis:
  secure:
    BINSTAR_TOKEN: TV2mYuXGyATJPQEPq7xPKzvlLATgo1Lzm3JO1nOw7DjJfEuENlGPtTTX0uXnMzK8ZHQCneGIrCFEWdydZx92Hiphqrdqjrg6ekpHM6BzXf8QE3cpb+u2h05Q9/eNkxpYnXUESZp4P7ENMsVlcoW8xfYrS0YEruuDSFxX3WCumhbzrCkKhVljXOF0WOWoTvJAPPvuolEzcd+UuocddBz5U+VYP15Rm9GZkW+vD5JVhxHRvOLLJe4k6Dgzq6KRABj1FvG9IiE3lfUhaLomI8+AhbmPx6sgPAcpqcOzVZfs/IPXotJOaLBJJOf/SGsklza6ExH7fDIFrj4nPOonY+5AnX0zzHNA3elcYVP3MRFpbFDFcqM5Vj3nFVWXyrbyIx1Sm/ap943bG737Fh4x1h5WmYoxCtF3wlocJk1sSIDwT0J0A1PIW3IX1ef61QPBL4rWIblXqQXZnplqj/Zm2Y+FK3oh3La/gzv9y0TF26NySd2Q1Nd6dMabiaLZL2KDaRw7o7kM8LxkGnBVpp1i84Ru4nxLI4hyimQlInV+jgg23oCVEJYSHUe72WjOq/IBbLvyREmMi17BlhimvXnuvzgpwZ6ow8AnAZ+4DGDGe64lWkLIKNALzBfzjmQ2odXJx4+1X51XI1Sz+3UM1gb7U/2KqT3nmlt3cUdTyBIWTubh4dY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
